'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Add Comment....
        '''</summary>
        Public ReadOnly Property Item_Edit_Comments_AddComment_Text() As String
            Get
                Return ResourceManager.GetString("Item_Edit_Comments_AddComment_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Review Comments....
        '''</summary>
        Public ReadOnly Property Item_Edit_Comments_ReviewComments_Text() As String
            Get
                Return ResourceManager.GetString("Item_Edit_Comments_ReviewComments_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Co_mments.
        '''</summary>
        Public ReadOnly Property Item_Edit_Comments_Text() As String
            Get
                Return ResourceManager.GetString("Item_Edit_Comments_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Copy.
        '''</summary>
        Public ReadOnly Property Item_Edit_Copy_Text() As String
            Get
                Return ResourceManager.GetString("Item_Edit_Copy_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cu_t.
        '''</summary>
        Public ReadOnly Property Item_Edit_Cut_Text() As String
            Get
                Return ResourceManager.GetString("Item_Edit_Cut_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _For {0}.
        '''</summary>
        Public ReadOnly Property Item_Edit_EditableRegions_Add_ForCurrentUser_Text() As String
            Get
                Return ResourceManager.GetString("Item_Edit_EditableRegions_Add_ForCurrentUser_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to For _Everyone.
        '''</summary>
        Public ReadOnly Property Item_Edit_EditableRegions_Add_ForEveryone_Text() As String
            Get
                Return ResourceManager.GetString("Item_Edit_EditableRegions_Add_ForEveryone_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Add.
        '''</summary>
        Public ReadOnly Property Item_Edit_EditableRegions_Add_Text() As String
            Get
                Return ResourceManager.GetString("Item_Edit_EditableRegions_Add_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _For {0}.
        '''</summary>
        Public ReadOnly Property Item_Edit_EditableRegions_Remove_ForCurrentUser_Text() As String
            Get
                Return ResourceManager.GetString("Item_Edit_EditableRegions_Remove_ForCurrentUser_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to For _Everyone.
        '''</summary>
        Public ReadOnly Property Item_Edit_EditableRegions_Remove_ForEveryone_Text() As String
            Get
                Return ResourceManager.GetString("Item_Edit_EditableRegions_Remove_ForEveryone_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Remove.
        '''</summary>
        Public ReadOnly Property Item_Edit_EditableRegions_Remove_Text() As String
            Get
                Return ResourceManager.GetString("Item_Edit_EditableRegions_Remove_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Editable Regions.
        '''</summary>
        Public ReadOnly Property Item_Edit_EditableRegions_Text() As String
            Get
                Return ResourceManager.GetString("Item_Edit_EditableRegions_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Find....
        '''</summary>
        Public ReadOnly Property Item_Edit_Find_Text() As String
            Get
                Return ResourceManager.GetString("Item_Edit_Find_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Paste.
        '''</summary>
        Public ReadOnly Property Item_Edit_Paste_Text() As String
            Get
                Return ResourceManager.GetString("Item_Edit_Paste_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Allow _Copy.
        '''</summary>
        Public ReadOnly Property Item_Edit_Permissions_AllowCopy_Text() As String
            Get
                Return ResourceManager.GetString("Item_Edit_Permissions_AllowCopy_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Allow _Editing Form Fields.
        '''</summary>
        Public ReadOnly Property Item_Edit_Permissions_AllowEditingFormFields_Text() As String
            Get
                Return ResourceManager.GetString("Item_Edit_Permissions_AllowEditingFormFields_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Allow _Formatting.
        '''</summary>
        Public ReadOnly Property Item_Edit_Permissions_AllowFormatting_Text() As String
            Get
                Return ResourceManager.GetString("Item_Edit_Permissions_AllowFormatting_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Allow Formatting _Styles.
        '''</summary>
        Public ReadOnly Property Item_Edit_Permissions_AllowFormattingStyles_Text() As String
            Get
                Return ResourceManager.GetString("Item_Edit_Permissions_AllowFormattingStyles_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Allow _Printing.
        '''</summary>
        Public ReadOnly Property Item_Edit_Permissions_AllowPrinting_Text() As String
            Get
                Return ResourceManager.GetString("Item_Edit_Permissions_AllowPrinting_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Read Only.
        '''</summary>
        Public ReadOnly Property Item_Edit_Permissions_ReadOnly_Text() As String
            Get
                Return ResourceManager.GetString("Item_Edit_Permissions_ReadOnly_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Permi_ssions.
        '''</summary>
        Public ReadOnly Property Item_Edit_Permissions_Text() As String
            Get
                Return ResourceManager.GetString("Item_Edit_Permissions_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pr_otect Document.
        '''</summary>
        Public ReadOnly Property Item_Edit_ProtectDocument_Text() As String
            Get
                Return ResourceManager.GetString("Item_Edit_ProtectDocument_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Redo.
        '''</summary>
        Public ReadOnly Property Item_Edit_Redo_Text() As String
            Get
                Return ResourceManager.GetString("Item_Edit_Redo_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Rep_lace....
        '''</summary>
        Public ReadOnly Property Item_Edit_Replace_Text() As String
            Get
                Return ResourceManager.GetString("Item_Edit_Replace_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select _All.
        '''</summary>
        Public ReadOnly Property Item_Edit_SelectAll_Text() As String
            Get
                Return ResourceManager.GetString("Item_Edit_SelectAll_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Edit.
        '''</summary>
        Public ReadOnly Property Item_Edit_Text() As String
            Get
                Return ResourceManager.GetString("Item_Edit_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Review Tracked Changes....
        '''</summary>
        Public ReadOnly Property Item_Edit_TrackedChanges_ReviewTrackedChanges_Text() As String
            Get
                Return ResourceManager.GetString("Item_Edit_TrackedChanges_ReviewTrackedChanges_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Trac_ked Changes.
        '''</summary>
        Public ReadOnly Property Item_Edit_TrackedChanges_Text() As String
            Get
                Return ResourceManager.GetString("Item_Edit_TrackedChanges_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Track Changes.
        '''</summary>
        Public ReadOnly Property Item_Edit_TrackedChanges_TrackChanges_Text() As String
            Get
                Return ResourceManager.GetString("Item_Edit_TrackedChanges_TrackChanges_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Undo.
        '''</summary>
        Public ReadOnly Property Item_Edit_Undo_Text() As String
            Get
                Return ResourceManager.GetString("Item_Edit_Undo_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Account Settings....
        '''</summary>
        Public ReadOnly Property Item_File_CurrentUser_AccountSettings_Text() As String
            Get
                Return ResourceManager.GetString("Item_File_CurrentUser_AccountSettings_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sign _Out.
        '''</summary>
        Public ReadOnly Property Item_File_CurrentUser_SignOut_Text() As String
            Get
                Return ResourceManager.GetString("Item_File_CurrentUser_SignOut_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0}.
        '''</summary>
        Public ReadOnly Property Item_File_CurrentUser_Text() As String
            Get
                Return ResourceManager.GetString("Item_File_CurrentUser_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to E_xit.
        '''</summary>
        Public ReadOnly Property Item_File_Exit_Text() As String
            Get
                Return ResourceManager.GetString("Item_File_Exit_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _New.
        '''</summary>
        Public ReadOnly Property Item_File_New_Text() As String
            Get
                Return ResourceManager.GetString("Item_File_New_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Open….
        '''</summary>
        Public ReadOnly Property Item_File_Open_Text() As String
            Get
                Return ResourceManager.GetString("Item_File_Open_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Page Se_tup….
        '''</summary>
        Public ReadOnly Property Item_File_PageSetup_Text() As String
            Get
                Return ResourceManager.GetString("Item_File_PageSetup_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Print....
        '''</summary>
        Public ReadOnly Property Item_File_Print_Text() As String
            Get
                Return ResourceManager.GetString("Item_File_Print_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Print _Quick.
        '''</summary>
        Public ReadOnly Property Item_File_PrintQuick_Text() As String
            Get
                Return ResourceManager.GetString("Item_File_PrintQuick_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Recent Files.
        '''</summary>
        Public ReadOnly Property Item_File_RecentFiles_Text() As String
            Get
                Return ResourceManager.GetString("Item_File_RecentFiles_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Save.
        '''</summary>
        Public ReadOnly Property Item_File_Save_Text() As String
            Get
                Return ResourceManager.GetString("Item_File_Save_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save _As….
        '''</summary>
        Public ReadOnly Property Item_File_SaveAs_Text() As String
            Get
                Return ResourceManager.GetString("Item_File_SaveAs_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sign _In....
        '''</summary>
        Public ReadOnly Property Item_File_SignIn_Text() As String
            Get
                Return ResourceManager.GetString("Item_File_SignIn_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _File.
        '''</summary>
        Public ReadOnly Property Item_File_Text() As String
            Get
                Return ResourceManager.GetString("Item_File_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Barcode....
        '''</summary>
        Public ReadOnly Property Item_Format_Barcode_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_Barcode_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Boo_kmark....
        '''</summary>
        Public ReadOnly Property Item_Format_Bookmark_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_Bookmark_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _1, 2, 3.
        '''</summary>
        Public ReadOnly Property Item_Format_BulletsAndNumbering_ArabicNumbers_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_BulletsAndNumbering_ArabicNumbers_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to As Structured _List.
        '''</summary>
        Public ReadOnly Property Item_Format_BulletsAndNumbering_AsStructuredList_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_BulletsAndNumbering_AsStructuredList_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to B_ullets.
        '''</summary>
        Public ReadOnly Property Item_Format_BulletsAndNumbering_Bullets_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_BulletsAndNumbering_Bullets_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _A, B, C.
        '''</summary>
        Public ReadOnly Property Item_Format_BulletsAndNumbering_CapitalLetters_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_BulletsAndNumbering_CapitalLetters_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Decrease Level.
        '''</summary>
        Public ReadOnly Property Item_Format_BulletsAndNumbering_DecreaseLevel_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_BulletsAndNumbering_DecreaseLevel_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to I_ncrease Level.
        '''</summary>
        Public ReadOnly Property Item_Format_BulletsAndNumbering_IncreaseLevel_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_BulletsAndNumbering_IncreaseLevel_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to a, _b, c.
        '''</summary>
        Public ReadOnly Property Item_Format_BulletsAndNumbering_Letters_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_BulletsAndNumbering_Letters_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Properties....
        '''</summary>
        Public ReadOnly Property Item_Format_BulletsAndNumbering_Properties_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_BulletsAndNumbering_Properties_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _I, II, III, IV.
        '''</summary>
        Public ReadOnly Property Item_Format_BulletsAndNumbering_RomanNumbers_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_BulletsAndNumbering_RomanNumbers_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to i, ii, iii, i_v.
        '''</summary>
        Public ReadOnly Property Item_Format_BulletsAndNumbering_SmallRomanNumbers_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_BulletsAndNumbering_SmallRomanNumbers_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bullets and _Numbering.
        '''</summary>
        Public ReadOnly Property Item_Format_BulletsAndNumbering_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_BulletsAndNumbering_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Character....
        '''</summary>
        Public ReadOnly Property Item_Format_Character_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_Character_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Colu_mns....
        '''</summary>
        Public ReadOnly Property Item_Format_Columns_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_Columns_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Edit....
        '''</summary>
        Public ReadOnly Property Item_Format_FormFields_Edit_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_FormFields_Edit_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enable Form _Validation.
        '''</summary>
        Public ReadOnly Property Item_Format_FormFields_EnableFormValidation_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_FormFields_EnableFormValidation_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Manage Conditional Instructions....
        '''</summary>
        Public ReadOnly Property Item_Format_FormFields_ManageConditionalInstructions_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_FormFields_ManageConditionalInstructions_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Form Fields.
        '''</summary>
        Public ReadOnly Property Item_Format_FormFields_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_FormFields_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Headers and Footers....
        '''</summary>
        Public ReadOnly Property Item_Format_HeadersAndFooters_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_HeadersAndFooters_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hype_rlink....
        '''</summary>
        Public ReadOnly Property Item_Format_Hyperlink_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_Hyperlink_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Image....
        '''</summary>
        Public ReadOnly Property Item_Format_Image_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_Image_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Language....
        '''</summary>
        Public ReadOnly Property Item_Format_Language_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_Language_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Page Bor_ders....
        '''</summary>
        Public ReadOnly Property Item_Format_PageBorders_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_PageBorders_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Page C_olor....
        '''</summary>
        Public ReadOnly Property Item_Format_PageColor_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_PageColor_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Page N_umber....
        '''</summary>
        Public ReadOnly Property Item_Format_PageNumberField_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_PageNumberField_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Paragraph....
        '''</summary>
        Public ReadOnly Property Item_Format_Paragraph_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_Paragraph_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Body Text.
        '''</summary>
        Public ReadOnly Property Item_Format_ParagraphStructureLevels_AddToParagraph_BodyText_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_ParagraphStructureLevels_AddToParagraph_BodyText_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Level {0}.
        '''</summary>
        Public ReadOnly Property Item_Format_ParagraphStructureLevels_AddToParagraph_Level_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_ParagraphStructureLevels_AddToParagraph_Level_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Add to Paragraph.
        '''</summary>
        Public ReadOnly Property Item_Format_ParagraphStructureLevels_AddToParagraph_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_ParagraphStructureLevels_AddToParagraph_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Body Text.
        '''</summary>
        Public ReadOnly Property Item_Format_ParagraphStructureLevels_CurrentParagraphStyle_BodyText_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_ParagraphStructureLevels_CurrentParagraphStyle_BodyText_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Level {0}.
        '''</summary>
        Public ReadOnly Property Item_Format_ParagraphStructureLevels_CurrentParagraphStyle_Level_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_ParagraphStructureLevels_CurrentParagraphStyle_Level_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Paragraph Style: {0}.
        '''</summary>
        Public ReadOnly Property Item_Format_ParagraphStructureLevels_CurrentParagraphStyle_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_ParagraphStructureLevels_CurrentParagraphStyle_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Paragraph Structure Le_vels.
        '''</summary>
        Public ReadOnly Property Item_Format_ParagraphStructureLevels_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_ParagraphStructureLevels_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sh_ape....
        '''</summary>
        Public ReadOnly Property Item_Format_Shape_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_Shape_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Styles....
        '''</summary>
        Public ReadOnly Property Item_Format_Styles_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_Styles_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tabl_e of Contents....
        '''</summary>
        Public ReadOnly Property Item_Format_TableOfContents_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_TableOfContents_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Tabs....
        '''</summary>
        Public ReadOnly Property Item_Format_Tabs_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_Tabs_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to F_ormat.
        '''</summary>
        Public ReadOnly Property Item_Format_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Te_xt Frame....
        '''</summary>
        Public ReadOnly Property Item_Format_TextFrame_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_TextFrame_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Barcode.
        '''</summary>
        Public ReadOnly Property Item_Insert_Barcode_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_Barcode_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Delete....
        '''</summary>
        Public ReadOnly Property Item_Insert_Bookmark_Delete_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_Bookmark_Delete_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Insert....
        '''</summary>
        Public ReadOnly Property Item_Insert_Bookmark_Insert_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_Bookmark_Insert_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Boo_kmark.
        '''</summary>
        Public ReadOnly Property Item_Insert_Bookmark_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_Bookmark_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _More Columns....
        '''</summary>
        Public ReadOnly Property Item_Insert_Columns_MoreColumns_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_Columns_MoreColumns_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _One.
        '''</summary>
        Public ReadOnly Property Item_Insert_Columns_One_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_Columns_One_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Columns.
        '''</summary>
        Public ReadOnly Property Item_Insert_Columns_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_Columns_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Two.
        '''</summary>
        Public ReadOnly Property Item_Insert_Columns_Two_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_Columns_Two_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _File....
        '''</summary>
        Public ReadOnly Property Item_Insert_File_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_File_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Insert.
        '''</summary>
        Public ReadOnly Property Item_Insert_Footer_Insert_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_Footer_Insert_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Remove.
        '''</summary>
        Public ReadOnly Property Item_Insert_Footer_Remove_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_Footer_Remove_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to F_ooter.
        '''</summary>
        Public ReadOnly Property Item_Insert_Footer_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_Footer_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Check Box.
        '''</summary>
        Public ReadOnly Property Item_Insert_FormField_CheckBox_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_FormField_CheckBox_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to C_ombo Box.
        '''</summary>
        Public ReadOnly Property Item_Insert_FormField_ComboBox_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_FormField_ComboBox_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to D_ate Form Field.
        '''</summary>
        Public ReadOnly Property Item_Insert_FormField_DateFormField_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_FormField_DateFormField_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to D_elete.
        '''</summary>
        Public ReadOnly Property Item_Insert_FormField_Delete_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_FormField_Delete_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Drop-Down List.
        '''</summary>
        Public ReadOnly Property Item_Insert_FormField_DropDownList_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_FormField_DropDownList_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fo_rm Field.
        '''</summary>
        Public ReadOnly Property Item_Insert_FormField_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_FormField_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Text Form Field.
        '''</summary>
        Public ReadOnly Property Item_Insert_FormField_TextFormField_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_FormField_TextFormField_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Insert.
        '''</summary>
        Public ReadOnly Property Item_Insert_Header_Insert_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_Header_Insert_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Remove.
        '''</summary>
        Public ReadOnly Property Item_Insert_Header_Remove_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_Header_Remove_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Header.
        '''</summary>
        Public ReadOnly Property Item_Insert_Header_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_Header_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hyp_erlink....
        '''</summary>
        Public ReadOnly Property Item_Insert_Hyperlink_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_Hyperlink_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Image....
        '''</summary>
        Public ReadOnly Property Item_Insert_Image_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_Image_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Columns.
        '''</summary>
        Public ReadOnly Property Item_Insert_PageBreaks_Column_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_PageBreaks_Column_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Page.
        '''</summary>
        Public ReadOnly Property Item_Insert_PageBreaks_Page_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_PageBreaks_Page_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to P_age Break.
        '''</summary>
        Public ReadOnly Property Item_Insert_PageBreaks_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_PageBreaks_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Text Wrapping.
        '''</summary>
        Public ReadOnly Property Item_Insert_PageBreaks_TextWrapping_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_PageBreaks_TextWrapping_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Delete.
        '''</summary>
        Public ReadOnly Property Item_Insert_PageNumber_Delete_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_PageNumber_Delete_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Insert.
        '''</summary>
        Public ReadOnly Property Item_Insert_PageNumber_Insert_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_PageNumber_Insert_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Page Number.
        '''</summary>
        Public ReadOnly Property Item_Insert_PageNumber_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_PageNumber_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Continuous.
        '''</summary>
        Public ReadOnly Property Item_Insert_SectionBreaks_Continuous_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_SectionBreaks_Continuous_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Next Page.
        '''</summary>
        Public ReadOnly Property Item_Insert_SectionBreaks_NextPage_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_SectionBreaks_NextPage_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sectio_n Break.
        '''</summary>
        Public ReadOnly Property Item_Insert_SectionBreaks_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_SectionBreaks_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Basic Shapes.
        '''</summary>
        Public ReadOnly Property Item_Insert_Shape_BasicShapes_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_Shape_BasicShapes_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Block _Arrows.
        '''</summary>
        Public ReadOnly Property Item_Insert_Shape_BlockArrows_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_Shape_BlockArrows_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Callouts.
        '''</summary>
        Public ReadOnly Property Item_Insert_Shape_Callouts_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_Shape_Callouts_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Drawing Canvas.
        '''</summary>
        Public ReadOnly Property Item_Insert_Shape_DrawingCanvas_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_Shape_DrawingCanvas_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Equation Shapes.
        '''</summary>
        Public ReadOnly Property Item_Insert_Shape_EquationShapes_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_Shape_EquationShapes_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Flowchart.
        '''</summary>
        Public ReadOnly Property Item_Insert_Shape_Flowchart_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_Shape_Flowchart_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Lines.
        '''</summary>
        Public ReadOnly Property Item_Insert_Shape_Lines_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_Shape_Lines_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Rectangles.
        '''</summary>
        Public ReadOnly Property Item_Insert_Shape_Rectangles_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_Shape_Rectangles_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Stars and Banners.
        '''</summary>
        Public ReadOnly Property Item_Insert_Shape_StarsAndBanners_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_Shape_StarsAndBanners_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Shape.
        '''</summary>
        Public ReadOnly Property Item_Insert_Shape_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_Shape_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sy_mbol....
        '''</summary>
        Public ReadOnly Property Item_Insert_Symbol_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_Symbol_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Delete.
        '''</summary>
        Public ReadOnly Property Item_Insert_TableOfContents_Delete_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_TableOfContents_Delete_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Insert.
        '''</summary>
        Public ReadOnly Property Item_Insert_TableOfContents_Insert_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_TableOfContents_Insert_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tab_le of Contents.
        '''</summary>
        Public ReadOnly Property Item_Insert_TableOfContents_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_TableOfContents_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Update.
        '''</summary>
        Public ReadOnly Property Item_Insert_TableOfContents_Update_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_TableOfContents_Update_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Insert.
        '''</summary>
        Public ReadOnly Property Item_Insert_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Text Frame.
        '''</summary>
        Public ReadOnly Property Item_Insert_TextFrame_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_TextFrame_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to C_ells.
        '''</summary>
        Public ReadOnly Property Item_Table_Delete_Cells_Text() As String
            Get
                Return ResourceManager.GetString("Item_Table_Delete_Cells_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Columns.
        '''</summary>
        Public ReadOnly Property Item_Table_Delete_Columns_Text() As String
            Get
                Return ResourceManager.GetString("Item_Table_Delete_Columns_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Rows.
        '''</summary>
        Public ReadOnly Property Item_Table_Delete_Rows_Text() As String
            Get
                Return ResourceManager.GetString("Item_Table_Delete_Rows_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Table.
        '''</summary>
        Public ReadOnly Property Item_Table_Delete_Table_Text() As String
            Get
                Return ResourceManager.GetString("Item_Table_Delete_Table_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Delete.
        '''</summary>
        Public ReadOnly Property Item_Table_Delete_Text() As String
            Get
                Return ResourceManager.GetString("Item_Table_Delete_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _A1 Reference Style.
        '''</summary>
        Public ReadOnly Property Item_Table_Formulas_A1ReferenceStyle_Text() As String
            Get
                Return ResourceManager.GetString("Item_Table_Formulas_A1ReferenceStyle_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Automatic _Calculation.
        '''</summary>
        Public ReadOnly Property Item_Table_Formulas_AutomaticCalculation_Text() As String
            Get
                Return ResourceManager.GetString("Item_Table_Formulas_AutomaticCalculation_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Edit Formula....
        '''</summary>
        Public ReadOnly Property Item_Table_Formulas_EditFormula_Text() As String
            Get
                Return ResourceManager.GetString("Item_Table_Formulas_EditFormula_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _R1C1 Reference Style.
        '''</summary>
        Public ReadOnly Property Item_Table_Formulas_R1C1ReferenceStyle_Text() As String
            Get
                Return ResourceManager.GetString("Item_Table_Formulas_R1C1ReferenceStyle_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Formulas.
        '''</summary>
        Public ReadOnly Property Item_Table_Formulas_Text() As String
            Get
                Return ResourceManager.GetString("Item_Table_Formulas_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Column To The _Left.
        '''</summary>
        Public ReadOnly Property Item_Table_Insert_ColumnToTheLeft_Text() As String
            Get
                Return ResourceManager.GetString("Item_Table_Insert_ColumnToTheLeft_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Column To The _Right.
        '''</summary>
        Public ReadOnly Property Item_Table_Insert_ColumnToTheRight_Text() As String
            Get
                Return ResourceManager.GetString("Item_Table_Insert_ColumnToTheRight_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Row _Above.
        '''</summary>
        Public ReadOnly Property Item_Table_Insert_RowAbove_Text() As String
            Get
                Return ResourceManager.GetString("Item_Table_Insert_RowAbove_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Row _Below.
        '''</summary>
        Public ReadOnly Property Item_Table_Insert_RowBelow_Text() As String
            Get
                Return ResourceManager.GetString("Item_Table_Insert_RowBelow_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Table....
        '''</summary>
        Public ReadOnly Property Item_Table_Insert_Table_Text() As String
            Get
                Return ResourceManager.GetString("Item_Table_Insert_Table_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Insert.
        '''</summary>
        Public ReadOnly Property Item_Table_Insert_Text() As String
            Get
                Return ResourceManager.GetString("Item_Table_Insert_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Merge Cells.
        '''</summary>
        Public ReadOnly Property Item_Table_MergeCells_Text() As String
            Get
                Return ResourceManager.GetString("Item_Table_MergeCells_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Properties....
        '''</summary>
        Public ReadOnly Property Item_Table_Properties_Text() As String
            Get
                Return ResourceManager.GetString("Item_Table_Properties_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to C_ell.
        '''</summary>
        Public ReadOnly Property Item_Table_Select_Cell_Text() As String
            Get
                Return ResourceManager.GetString("Item_Table_Select_Cell_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Column.
        '''</summary>
        Public ReadOnly Property Item_Table_Select_Column_Text() As String
            Get
                Return ResourceManager.GetString("Item_Table_Select_Column_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Row.
        '''</summary>
        Public ReadOnly Property Item_Table_Select_Row_Text() As String
            Get
                Return ResourceManager.GetString("Item_Table_Select_Row_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Table.
        '''</summary>
        Public ReadOnly Property Item_Table_Select_Table_Text() As String
            Get
                Return ResourceManager.GetString("Item_Table_Select_Table_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Select.
        '''</summary>
        Public ReadOnly Property Item_Table_Select_Text() As String
            Get
                Return ResourceManager.GetString("Item_Table_Select_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Split _Cells.
        '''</summary>
        Public ReadOnly Property Item_Table_SplitCells_Text() As String
            Get
                Return ResourceManager.GetString("Item_Table_SplitCells_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Above.
        '''</summary>
        Public ReadOnly Property Item_Table_SplitTable_Above_Text() As String
            Get
                Return ResourceManager.GetString("Item_Table_SplitTable_Above_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Below.
        '''</summary>
        Public ReadOnly Property Item_Table_SplitTable_Below_Text() As String
            Get
                Return ResourceManager.GetString("Item_Table_SplitTable_Below_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Split _Table.
        '''</summary>
        Public ReadOnly Property Item_Table_SplitTable_Text() As String
            Get
                Return ResourceManager.GetString("Item_Table_SplitTable_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Table.
        '''</summary>
        Public ReadOnly Property Item_Table_Text() As String
            Get
                Return ResourceManager.GetString("Item_Table_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to B_ookmark Markers.
        '''</summary>
        Public ReadOnly Property Item_View_BookmarkMarkers_Text() As String
            Get
                Return ResourceManager.GetString("Item_View_BookmarkMarkers_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Button Bar.
        '''</summary>
        Public ReadOnly Property Item_View_ButtonBar_Text() As String
            Get
                Return ResourceManager.GetString("Item_View_ButtonBar_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Always.
        '''</summary>
        Public ReadOnly Property Item_View_Comments_Always_Text() As String
            Get
                Return ResourceManager.GetString("Item_View_Comments_Always_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Current.
        '''</summary>
        Public ReadOnly Property Item_View_Comments_Current_Text() As String
            Get
                Return ResourceManager.GetString("Item_View_Comments_Current_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Never.
        '''</summary>
        Public ReadOnly Property Item_View_Comments_Never_Text() As String
            Get
                Return ResourceManager.GetString("Item_View_Comments_Never_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Co_mments.
        '''</summary>
        Public ReadOnly Property Item_View_Comments_Text() As String
            Get
                Return ResourceManager.GetString("Item_View_Comments_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Control Chars.
        '''</summary>
        Public ReadOnly Property Item_View_ControlChars_Text() As String
            Get
                Return ResourceManager.GetString("Item_View_ControlChars_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Draft.
        '''</summary>
        Public ReadOnly Property Item_View_Draft_Text() As String
            Get
                Return ResourceManager.GetString("Item_View_Draft_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dra_wing Marker Lines.
        '''</summary>
        Public ReadOnly Property Item_View_DrawingMarkerLines_Text() As String
            Get
                Return ResourceManager.GetString("Item_View_DrawingMarkerLines_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Always.
        '''</summary>
        Public ReadOnly Property Item_View_EditableRegions_Always_Text() As String
            Get
                Return ResourceManager.GetString("Item_View_EditableRegions_Always_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Current.
        '''</summary>
        Public ReadOnly Property Item_View_EditableRegions_Current_Text() As String
            Get
                Return ResourceManager.GetString("Item_View_EditableRegions_Current_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Never.
        '''</summary>
        Public ReadOnly Property Item_View_EditableRegions_Never_Text() As String
            Get
                Return ResourceManager.GetString("Item_View_EditableRegions_Never_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Editiable Regions.
        '''</summary>
        Public ReadOnly Property Item_View_EditableRegions_Text() As String
            Get
                Return ResourceManager.GetString("Item_View_EditableRegions_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Horizontal Ruler.
        '''</summary>
        Public ReadOnly Property Item_View_HorizontalRuler_Text() As String
            Get
                Return ResourceManager.GetString("Item_View_HorizontalRuler_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Page Layout.
        '''</summary>
        Public ReadOnly Property Item_View_PageLayout_Text() As String
            Get
                Return ResourceManager.GetString("Item_View_PageLayout_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Right to Left Layout.
        '''</summary>
        Public ReadOnly Property Item_View_RightToLeftLayout_Text() As String
            Get
                Return ResourceManager.GetString("Item_View_RightToLeftLayout_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Status Bar.
        '''</summary>
        Public ReadOnly Property Item_View_StatusBar_Text() As String
            Get
                Return ResourceManager.GetString("Item_View_StatusBar_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Table Gridlines.
        '''</summary>
        Public ReadOnly Property Item_View_TableGridlines_Text() As String
            Get
                Return ResourceManager.GetString("Item_View_TableGridlines_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _View.
        '''</summary>
        Public ReadOnly Property Item_View_Text() As String
            Get
                Return ResourceManager.GetString("Item_View_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Text _Frame Marker Lines.
        '''</summary>
        Public ReadOnly Property Item_View_TextFrameMarkerLines_Text() As String
            Get
                Return ResourceManager.GetString("Item_View_TextFrameMarkerLines_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tr_acked Changes.
        '''</summary>
        Public ReadOnly Property Item_View_TrackedChanges_Text() As String
            Get
                Return ResourceManager.GetString("Item_View_TrackedChanges_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Vertical Ruler.
        '''</summary>
        Public ReadOnly Property Item_View_VerticalRuler_Text() As String
            Get
                Return ResourceManager.GetString("Item_View_VerticalRuler_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0}%.
        '''</summary>
        Public ReadOnly Property Item_View_Zoom_Factor_Text() As String
            Get
                Return ResourceManager.GetString("Item_View_Zoom_Factor_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Zoom.
        '''</summary>
        Public ReadOnly Property Item_View_Zoom_Text() As String
            Get
                Return ResourceManager.GetString("Item_View_Zoom_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TX Text Control Words.
        '''</summary>
        Public ReadOnly Property MainWindow_Caption_Product() As String
            Get
                Return ResourceManager.GetString("MainWindow_Caption_Product", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [untitled].
        '''</summary>
        Public ReadOnly Property MainWindow_Caption_Untitled() As String
            Get
                Return ResourceManager.GetString("MainWindow_Caption_Untitled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add Comment.
        '''</summary>
        Public ReadOnly Property MessageBox_AddComment_Error_Caption() As String
            Get
                Return ResourceManager.GetString("MessageBox_AddComment_Error_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An unexpected error has occurred..
        '''</summary>
        Public ReadOnly Property MessageBox_AddComment_Error_Text() As String
            Get
                Return ResourceManager.GetString("MessageBox_AddComment_Error_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add Comment.
        '''</summary>
        Public ReadOnly Property MessageBox_AddComment_NoSelection_Caption() As String
            Get
                Return ResourceManager.GetString("MessageBox_AddComment_NoSelection_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to First select a part of the document to add a comment about it..
        '''</summary>
        Public ReadOnly Property MessageBox_AddComment_NoSelection_Text() As String
            Get
                Return ResourceManager.GetString("MessageBox_AddComment_NoSelection_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add Comment.
        '''</summary>
        Public ReadOnly Property MessageBox_AddComment_PositionInvalid_Caption() As String
            Get
                Return ResourceManager.GetString("MessageBox_AddComment_PositionInvalid_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The comment wasn&apos;t inserted because the specified position values (start and/or length) are invalid..
        '''</summary>
        Public ReadOnly Property MessageBox_AddComment_PositionInvalid_Text() As String
            Get
                Return ResourceManager.GetString("MessageBox_AddComment_PositionInvalid_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add Comment.
        '''</summary>
        Public ReadOnly Property MessageBox_AddComment_SelectionTooComplex_Caption() As String
            Get
                Return ResourceManager.GetString("MessageBox_AddComment_SelectionTooComplex_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The comment wasn&apos;t inserted because the selection is too complex. It is not a continuous sequence of characters..
        '''</summary>
        Public ReadOnly Property MessageBox_AddComment_SelectionTooComplex_Text() As String
            Get
                Return ResourceManager.GetString("MessageBox_AddComment_SelectionTooComplex_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Editable Regions.
        '''</summary>
        Public ReadOnly Property MessageBox_AddEditableRegion_Error_Caption() As String
            Get
                Return ResourceManager.GetString("MessageBox_AddEditableRegion_Error_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An unexpected error has occurred..
        '''</summary>
        Public ReadOnly Property MessageBox_AddEditableRegion_Error_Text() As String
            Get
                Return ResourceManager.GetString("MessageBox_AddEditableRegion_Error_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Editable Regions.
        '''</summary>
        Public ReadOnly Property MessageBox_AddEditableRegion_NoSelection_Caption() As String
            Get
                Return ResourceManager.GetString("MessageBox_AddEditableRegion_NoSelection_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to First select a part of the document and then choose the user who can freely edit it..
        '''</summary>
        Public ReadOnly Property MessageBox_AddEditableRegion_NoSelection_Text() As String
            Get
                Return ResourceManager.GetString("MessageBox_AddEditableRegion_NoSelection_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Editable Regions.
        '''</summary>
        Public ReadOnly Property MessageBox_AddEditableRegion_PositionInvalid_Caption() As String
            Get
                Return ResourceManager.GetString("MessageBox_AddEditableRegion_PositionInvalid_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The editable region wasn&apos;t inserted because the specified position values (start and/or length) are invalid..
        '''</summary>
        Public ReadOnly Property MessageBox_AddEditableRegion_PositionInvalid_Text() As String
            Get
                Return ResourceManager.GetString("MessageBox_AddEditableRegion_PositionInvalid_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Editable Regions.
        '''</summary>
        Public ReadOnly Property MessageBox_AddEditableRegion_SelectionTooComplex_Caption() As String
            Get
                Return ResourceManager.GetString("MessageBox_AddEditableRegion_SelectionTooComplex_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The editable region wasn&apos;t inserted because the selection is too complex. It is not a continuous sequence of characters..
        '''</summary>
        Public ReadOnly Property MessageBox_AddEditableRegion_SelectionTooComplex_Text() As String
            Get
                Return ResourceManager.GetString("MessageBox_AddEditableRegion_SelectionTooComplex_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The following exception is thrown:
        '''	
        '''&quot;{0}&quot;
        '''
        '''To get help, please visit the Text Control Support at www.textcontrol.com..
        '''</summary>
        Public ReadOnly Property MessageBox_Application_ThreadException_Text() As String
            Get
                Return ResourceManager.GetString("MessageBox_Application_ThreadException_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Change Form Layout.
        '''</summary>
        Public ReadOnly Property MessageBox_ChangeFormLayout_Caption() As String
            Get
                Return ResourceManager.GetString("MessageBox_ChangeFormLayout_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to To change the program&apos;s view to a {0} to {1} text appearance, the application must be restarted. 
        '''Click OK to restart or Cancel to not restart the program..
        '''</summary>
        Public ReadOnly Property MessageBox_ChangeFormLayout_Text() As String
            Get
                Return ResourceManager.GetString("MessageBox_ChangeFormLayout_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Open Hyperlink.
        '''</summary>
        Public ReadOnly Property MessageBox_OpenHyperlink_CouldNotOpenLink_Caption() As String
            Get
                Return ResourceManager.GetString("MessageBox_OpenHyperlink_CouldNotOpenLink_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Could not open link to &apos;{0}&apos;..
        '''</summary>
        Public ReadOnly Property MessageBox_OpenHyperlink_CouldNotOpenLink_Text() As String
            Get
                Return ResourceManager.GetString("MessageBox_OpenHyperlink_CouldNotOpenLink_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Open linked File.
        '''</summary>
        Public ReadOnly Property MessageBox_OpenHyperlink_FileDoesNotExist_Caption() As String
            Get
                Return ResourceManager.GetString("MessageBox_OpenHyperlink_FileDoesNotExist_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The linked file &apos;{0}&apos; does not exist..
        '''</summary>
        Public ReadOnly Property MessageBox_OpenHyperlink_FileDoesNotExist_Text() As String
            Get
                Return ResourceManager.GetString("MessageBox_OpenHyperlink_FileDoesNotExist_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Open Recent File.
        '''</summary>
        Public ReadOnly Property MessageBox_OpenRecentFile_FileDoesNotExist_Caption() As String
            Get
                Return ResourceManager.GetString("MessageBox_OpenRecentFile_FileDoesNotExist_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The selected file does not exist. Do you want to remove it from the list of recent files?.
        '''</summary>
        Public ReadOnly Property MessageBox_OpenRecentFile_FileDoesNotExist_Text() As String
            Get
                Return ResourceManager.GetString("MessageBox_OpenRecentFile_FileDoesNotExist_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Incorrect Password.
        '''</summary>
        Public ReadOnly Property MessageBox_PasswordDialog_IncorrectPassword_Caption() As String
            Get
                Return ResourceManager.GetString("MessageBox_PasswordDialog_IncorrectPassword_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The entered password is incorrect..
        '''</summary>
        Public ReadOnly Property MessageBox_PasswordDialog_IncorrectPassword_Text() As String
            Get
                Return ResourceManager.GetString("MessageBox_PasswordDialog_IncorrectPassword_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to left.
        '''</summary>
        Public ReadOnly Property MessageBox_SaveDirtyDocumentBeforeRestart_Left() As String
            Get
                Return ResourceManager.GetString("MessageBox_SaveDirtyDocumentBeforeRestart_Left", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to right.
        '''</summary>
        Public ReadOnly Property MessageBox_SaveDirtyDocumentBeforeRestart_Right() As String
            Get
                Return ResourceManager.GetString("MessageBox_SaveDirtyDocumentBeforeRestart_Right", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to To change the program&apos;s view to a {0} to {1} text appearance, the application must be restarted. Also, changes to &apos;{2}&apos; were not saved.
        '''Click Yes to save these changes and restart, No to restart without saving, or Cancel to not restart..
        '''</summary>
        Public ReadOnly Property MessageBox_SaveDirtyDocumentBeforeRestart_ToFile() As String
            Get
                Return ResourceManager.GetString("MessageBox_SaveDirtyDocumentBeforeRestart_ToFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to To change the program&apos;s view to a {0} to {1} text appearance, the application must be restarted. Also, changes to the document were not saved.
        '''Click Yes to save these changes and restart, No to restart without saving, or Cancel to not restart..
        '''</summary>
        Public ReadOnly Property MessageBox_SaveDirtyDocumentBeforeRestart_Untitled() As String
            Get
                Return ResourceManager.GetString("MessageBox_SaveDirtyDocumentBeforeRestart_Untitled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Exit.
        '''</summary>
        Public ReadOnly Property MessageBox_SaveDirtyDocumentOnExit_Caption() As String
            Get
                Return ResourceManager.GetString("MessageBox_SaveDirtyDocumentOnExit_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you want to save changes to &apos;{0}&apos; before the program closes? 
        '''Click Yes to save and close, No to close without saving, or Cancel to not close..
        '''</summary>
        Public ReadOnly Property MessageBox_SaveDirtyDocumentOnExit_ToFile() As String
            Get
                Return ResourceManager.GetString("MessageBox_SaveDirtyDocumentOnExit_ToFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you want to save the document before the program closes? 
        '''Click Yes to save and close, No to close without saving, or Cancel to not close..
        '''</summary>
        Public ReadOnly Property MessageBox_SaveDirtyDocumentOnExit_Untitled() As String
            Get
                Return ResourceManager.GetString("MessageBox_SaveDirtyDocumentOnExit_Untitled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New.
        '''</summary>
        Public ReadOnly Property MessageBox_SaveDirtyDocumentOnNew_Caption() As String
            Get
                Return ResourceManager.GetString("MessageBox_SaveDirtyDocumentOnNew_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you want to save changes to &apos;{0}&apos; before a new document is created? 
        '''Click Yes to save and create, No to create without saving, or Cancel to not to create a new document..
        '''</summary>
        Public ReadOnly Property MessageBox_SaveDirtyDocumentOnNew_ToFile() As String
            Get
                Return ResourceManager.GetString("MessageBox_SaveDirtyDocumentOnNew_ToFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you want to save the document before a new document is created? 
        '''Click Yes to save and create, No to create without saving, or Cancel to not to create a new document..
        '''</summary>
        Public ReadOnly Property MessageBox_SaveDirtyDocumentOnNew_Untitled() As String
            Get
                Return ResourceManager.GetString("MessageBox_SaveDirtyDocumentOnNew_Untitled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Open.
        '''</summary>
        Public ReadOnly Property MessageBox_SaveDirtyDocumentOnOpen_Caption() As String
            Get
                Return ResourceManager.GetString("MessageBox_SaveDirtyDocumentOnOpen_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you want to save changes to &apos;{0}&apos; before the new document is opened? 
        '''Click Yes to save and open, No to open without saving, or Cancel to not to open the new document..
        '''</summary>
        Public ReadOnly Property MessageBox_SaveDirtyDocumentOnOpen_ToFile() As String
            Get
                Return ResourceManager.GetString("MessageBox_SaveDirtyDocumentOnOpen_ToFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you want to save the document before the new document is opened? 
        '''Click Yes to save and open, No to open without saving, or Cancel to not to open the new document..
        '''</summary>
        Public ReadOnly Property MessageBox_SaveDirtyDocumentOnOpen_Untitled() As String
            Get
                Return ResourceManager.GetString("MessageBox_SaveDirtyDocumentOnOpen_Untitled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Table Of Contents.
        '''</summary>
        Public ReadOnly Property MessageBox_UpdateTableOfContents_NoContents_Caption() As String
            Get
                Return ResourceManager.GetString("MessageBox_UpdateTableOfContents_NoContents_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No table of contents entries found..
        '''</summary>
        Public ReadOnly Property MessageBox_UpdateTableOfContents_NoContents_Text() As String
            Get
                Return ResourceManager.GetString("MessageBox_UpdateTableOfContents_NoContents_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sign Out.
        '''</summary>
        Public ReadOnly Property MessageBox_UserAccess_SignOut_Caption() As String
            Get
                Return ResourceManager.GetString("MessageBox_UserAccess_SignOut_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} was successfully signed out..
        '''</summary>
        Public ReadOnly Property MessageBox_UserAccess_SignOut_Text() As String
            Get
                Return ResourceManager.GetString("MessageBox_UserAccess_SignOut_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to By deleting the account, the current user will be signed out. Click OK to proceed or Cancel to not delete the account..
        '''</summary>
        Public ReadOnly Property MessageBox_UserAccessDialogDeleteAccount_Text() As String
            Get
                Return ResourceManager.GetString("MessageBox_UserAccessDialogDeleteAccount_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The entered password does not match the given user&apos;s password..
        '''</summary>
        Public ReadOnly Property MessageBox_UserAccessDialogIncorrectPassword_Text() As String
            Get
                Return ResourceManager.GetString("MessageBox_UserAccessDialogIncorrectPassword_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hide Tracked Changes.
        '''</summary>
        Public ReadOnly Property Method_SetTrackedChangesHighlightMode_HideTrackedChanges() As String
            Get
                Return ResourceManager.GetString("Method_SetTrackedChangesHighlightMode_HideTrackedChanges", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Highlight Tracked Changes.
        '''</summary>
        Public ReadOnly Property Method_SetTrackedChangesHighlightMode_HighlightTrackedChanges() As String
            Get
                Return ResourceManager.GetString("Method_SetTrackedChangesHighlightMode_HighlightTrackedChanges", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancel.
        '''</summary>
        Public ReadOnly Property PasswordDialog_Cancel() As String
            Get
                Return ResourceManager.GetString("PasswordDialog_Cancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Password.
        '''</summary>
        Public ReadOnly Property PasswordDialog_Caption() As String
            Get
                Return ResourceManager.GetString("PasswordDialog_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter a password to open the document..
        '''</summary>
        Public ReadOnly Property PasswordDialog_EnterPassword() As String
            Get
                Return ResourceManager.GetString("PasswordDialog_EnterPassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OK.
        '''</summary>
        Public ReadOnly Property PasswordDialog_OK() As String
            Get
                Return ResourceManager.GetString("PasswordDialog_OK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Password:.
        '''</summary>
        Public ReadOnly Property PasswordDialog_Password() As String
            Get
                Return ResourceManager.GetString("PasswordDialog_Password", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The document &apos;{0}&apos; is protected..
        '''</summary>
        Public ReadOnly Property PasswordDialog_ProtectedDocument() As String
            Get
                Return ResourceManager.GetString("PasswordDialog_ProtectedDocument", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Column: .
        '''</summary>
        Public ReadOnly Property StatusBar_Column() As String
            Get
                Return ResourceManager.GetString("StatusBar_Column", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Line: .
        '''</summary>
        Public ReadOnly Property StatusBar_Line() As String
            Get
                Return ResourceManager.GetString("StatusBar_Line", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Page: .
        '''</summary>
        Public ReadOnly Property StatusBar_Page() As String
            Get
                Return ResourceManager.GetString("StatusBar_Page", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Section: .
        '''</summary>
        Public ReadOnly Property StatusBar_Section() As String
            Get
                Return ResourceManager.GetString("StatusBar_Section", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Account Settings.
        '''</summary>
        Public ReadOnly Property UserAccessDialog_AccountSettings_Caption() As String
            Get
                Return ResourceManager.GetString("UserAccessDialog_AccountSettings_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Confirm Password:.
        '''</summary>
        Public ReadOnly Property UserAccessDialog_AccountSettings_ConfirmPassword() As String
            Get
                Return ResourceManager.GetString("UserAccessDialog_AccountSettings_ConfirmPassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Delete Account.
        '''</summary>
        Public ReadOnly Property UserAccessDialog_AccountSettings_Delete() As String
            Get
                Return ResourceManager.GetString("UserAccessDialog_AccountSettings_Delete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _New Password:.
        '''</summary>
        Public ReadOnly Property UserAccessDialog_AccountSettings_NewPassword() As String
            Get
                Return ResourceManager.GetString("UserAccessDialog_AccountSettings_NewPassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Old Password:.
        '''</summary>
        Public ReadOnly Property UserAccessDialog_AccountSettings_OldPassword() As String
            Get
                Return ResourceManager.GetString("UserAccessDialog_AccountSettings_OldPassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancel.
        '''</summary>
        Public ReadOnly Property UserAccessDialog_Cancel() As String
            Get
                Return ResourceManager.GetString("UserAccessDialog_Cancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Create New User Account.
        '''</summary>
        Public ReadOnly Property UserAccessDialog_CreateAccount_Caption() As String
            Get
                Return ResourceManager.GetString("UserAccessDialog_CreateAccount_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Confirm Password:.
        '''</summary>
        Public ReadOnly Property UserAccessDialog_CreateAccount_ConfirmPassword() As String
            Get
                Return ResourceManager.GetString("UserAccessDialog_CreateAccount_ConfirmPassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _New Password:.
        '''</summary>
        Public ReadOnly Property UserAccessDialog_CreateAccount_NewPassword() As String
            Get
                Return ResourceManager.GetString("UserAccessDialog_CreateAccount_NewPassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OK.
        '''</summary>
        Public ReadOnly Property UserAccessDialog_OK() As String
            Get
                Return ResourceManager.GetString("UserAccessDialog_OK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sign In.
        '''</summary>
        Public ReadOnly Property UserAccessDialog_SignIn_Caption() As String
            Get
                Return ResourceManager.GetString("UserAccessDialog_SignIn_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Password:.
        '''</summary>
        Public ReadOnly Property UserAccessDialog_SignIn_Password() As String
            Get
                Return ResourceManager.GetString("UserAccessDialog_SignIn_Password", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
