'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to this Sample.
        '''</summary>
        Public ReadOnly Property AboutButton_ToolTip_Description() As String
            Get
                Return ResourceManager.GetString("AboutButton_ToolTip_Description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Open Sample Template.
        '''</summary>
        Public ReadOnly Property ApplicationMenu_OpenSampleTemplate() As String
            Get
                Return ResourceManager.GetString("ApplicationMenu_OpenSampleTemplate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to M.
        '''</summary>
        Public ReadOnly Property ApplicationMenu_OpenSampleTemplate_KeyTip() As String
            Get
                Return ResourceManager.GetString("ApplicationMenu_OpenSampleTemplate_KeyTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Provides three sample templates that can be combined with the reporting tab&apos;s database sample to show a typical merge process..
        '''</summary>
        Public ReadOnly Property ApplicationMenu_OpenSampleTemplate_ToolTip_Description() As String
            Get
                Return ResourceManager.GetString("ApplicationMenu_OpenSampleTemplate_ToolTip_Description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Open Sample Template.
        '''</summary>
        Public ReadOnly Property ApplicationMenu_OpenSampleTemplate_ToolTip_Title() As String
            Get
                Return ResourceManager.GetString("ApplicationMenu_OpenSampleTemplate_ToolTip_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Recent Files.
        '''</summary>
        Public ReadOnly Property ApplicationMenu_ResentFiles() As String
            Get
                Return ResourceManager.GetString("ApplicationMenu_ResentFiles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sample Invoice Template.
        '''</summary>
        Public ReadOnly Property ApplicationMenu_SampleInvoiceTemplate() As String
            Get
                Return ResourceManager.GetString("ApplicationMenu_SampleInvoiceTemplate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to I.
        '''</summary>
        Public ReadOnly Property ApplicationMenu_SampleInvoiceTemplate_KeyTip() As String
            Get
                Return ResourceManager.GetString("ApplicationMenu_SampleInvoiceTemplate_KeyTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sample Packing List Template.
        '''</summary>
        Public ReadOnly Property ApplicationMenu_SamplePackingListTemplate() As String
            Get
                Return ResourceManager.GetString("ApplicationMenu_SamplePackingListTemplate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to P.
        '''</summary>
        Public ReadOnly Property ApplicationMenu_SamplePackingListTemplate_KeyTip() As String
            Get
                Return ResourceManager.GetString("ApplicationMenu_SamplePackingListTemplate_KeyTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sample Shipping Label Template.
        '''</summary>
        Public ReadOnly Property ApplicationMenu_SampleShippingLabelTemplate() As String
            Get
                Return ResourceManager.GetString("ApplicationMenu_SampleShippingLabelTemplate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to S.
        '''</summary>
        Public ReadOnly Property ApplicationMenu_SampleShippingLabelTemplate_KeyTip() As String
            Get
                Return ResourceManager.GetString("ApplicationMenu_SampleShippingLabelTemplate_KeyTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chart Tools.
        '''</summary>
        Public ReadOnly Property ContextualTabGroup_ChartTools() As String
            Get
                Return ResourceManager.GetString("ContextualTabGroup_ChartTools", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Frame Tools.
        '''</summary>
        Public ReadOnly Property ContextualTabGroup_FrameTools() As String
            Get
                Return ResourceManager.GetString("ContextualTabGroup_FrameTools", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reporting.
        '''</summary>
        Public ReadOnly Property ContextualTabGroup_Reporting() As String
            Get
                Return ResourceManager.GetString("ContextualTabGroup_Reporting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Table Tools.
        '''</summary>
        Public ReadOnly Property ContextualTabGroup_TableTools() As String
            Get
                Return ResourceManager.GetString("ContextualTabGroup_TableTools", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Export Merge Result....
        '''</summary>
        Public ReadOnly Property ExportMergeResult() As String
            Get
                Return ResourceManager.GetString("ExportMergeResult", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to X.
        '''</summary>
        Public ReadOnly Property ExportMergeResult_KeyTip() As String
            Get
                Return ResourceManager.GetString("ExportMergeResult_KeyTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Opens a dialog to export the merge result..
        '''</summary>
        Public ReadOnly Property ExportMergeResult_ToolTip_Description() As String
            Get
                Return ResourceManager.GetString("ExportMergeResult_ToolTip_Description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Export Merge Result.
        '''</summary>
        Public ReadOnly Property ExportMergeResult_ToolTip_Title() As String
            Get
                Return ResourceManager.GetString("ExportMergeResult_ToolTip_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancel.
        '''</summary>
        Public ReadOnly Property ExportMergeResultDialog_Cancel() As String
            Get
                Return ResourceManager.GetString("ExportMergeResultDialog_Cancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Export Merge Result.
        '''</summary>
        Public ReadOnly Property ExportMergeResultDialog_Caption() As String
            Get
                Return ResourceManager.GetString("ExportMergeResultDialog_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Directory:.
        '''</summary>
        Public ReadOnly Property ExportMergeResultDialog_Directory() As String
            Get
                Return ResourceManager.GetString("ExportMergeResultDialog_Directory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to File _Prefix:.
        '''</summary>
        Public ReadOnly Property ExportMergeResultDialog_FilePrefix() As String
            Get
                Return ResourceManager.GetString("ExportMergeResultDialog_FilePrefix", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Format:.
        '''</summary>
        Public ReadOnly Property ExportMergeResultDialog_Format() As String
            Get
                Return ResourceManager.GetString("ExportMergeResultDialog_Format", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Microsoft Word 97-2003 (*{0}).
        '''</summary>
        Public ReadOnly Property ExportMergeResultDialog_Format_DOC() As String
            Get
                Return ResourceManager.GetString("ExportMergeResultDialog_Format_DOC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Microsoft Word (*{0}).
        '''</summary>
        Public ReadOnly Property ExportMergeResultDialog_Format_DOCX() As String
            Get
                Return ResourceManager.GetString("ExportMergeResultDialog_Format_DOCX", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hypertext Markup Language (*{0}).
        '''</summary>
        Public ReadOnly Property ExportMergeResultDialog_Format_HTML() As String
            Get
                Return ResourceManager.GetString("ExportMergeResultDialog_Format_HTML", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Adobe PDF (*{0}).
        '''</summary>
        Public ReadOnly Property ExportMergeResultDialog_Format_PDF() As String
            Get
                Return ResourceManager.GetString("ExportMergeResultDialog_Format_PDF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Rich Text Format (*{0}).
        '''</summary>
        Public ReadOnly Property ExportMergeResultDialog_Format_RTF() As String
            Get
                Return ResourceManager.GetString("ExportMergeResultDialog_Format_RTF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TX Text Control Format (*{0}).
        '''</summary>
        Public ReadOnly Property ExportMergeResultDialog_Format_TX() As String
            Get
                Return ResourceManager.GetString("ExportMergeResultDialog_Format_TX", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Plain Text (*{0}).
        '''</summary>
        Public ReadOnly Property ExportMergeResultDialog_Format_TXT() As String
            Get
                Return ResourceManager.GetString("ExportMergeResultDialog_Format_TXT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OK.
        '''</summary>
        Public ReadOnly Property ExportMergeResultDialog_OK() As String
            Get
                Return ResourceManager.GetString("ExportMergeResultDialog_OK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Open directory after export.
        '''</summary>
        Public ReadOnly Property ExportMergeResultDialog_openDirectory() As String
            Get
                Return ResourceManager.GetString("ExportMergeResultDialog_openDirectory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TX Text Control Words.
        '''</summary>
        Public ReadOnly Property MainWindow_Caption_Product() As String
            Get
                Return ResourceManager.GetString("MainWindow_Caption_Product", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [untitled].
        '''</summary>
        Public ReadOnly Property MainWindow_Caption_Untitled() As String
            Get
                Return ResourceManager.GetString("MainWindow_Caption_Untitled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Merge.
        '''</summary>
        Public ReadOnly Property Merge() As String
            Get
                Return ResourceManager.GetString("Merge", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to L.
        '''</summary>
        Public ReadOnly Property Merge_KeyTip() As String
            Get
                Return ResourceManager.GetString("Merge_KeyTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Merge and Export.
        '''</summary>
        Public ReadOnly Property MergeAndExport() As String
            Get
                Return ResourceManager.GetString("MergeAndExport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to P.
        '''</summary>
        Public ReadOnly Property MergeAndExport_KeyTip() As String
            Get
                Return ResourceManager.GetString("MergeAndExport_KeyTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Starts the merge process and opens the &apos;Results&apos; tab to show and export the created documents..
        '''</summary>
        Public ReadOnly Property MergeAndExport_ToolTip_Description() As String
            Get
                Return ResourceManager.GetString("MergeAndExport_ToolTip_Description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Merge and Export.
        '''</summary>
        Public ReadOnly Property MergeAndExport_ToolTip_Title() As String
            Get
                Return ResourceManager.GetString("MergeAndExport_ToolTip_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please Wait.
        '''</summary>
        Public ReadOnly Property MergeAndWaitDialog_Caption() As String
            Get
                Return ResourceManager.GetString("MergeAndWaitDialog_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Merging.....
        '''</summary>
        Public ReadOnly Property MergeAndWaitDialog_Merging() As String
            Get
                Return ResourceManager.GetString("MergeAndWaitDialog_Merging", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to   Results  .
        '''</summary>
        Public ReadOnly Property MergeResultsTab() As String
            Get
                Return ResourceManager.GetString("MergeResultsTab", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Exit.
        '''</summary>
        Public ReadOnly Property MergeResultsTab_Exit() As String
            Get
                Return ResourceManager.GetString("MergeResultsTab_Exit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to E.
        '''</summary>
        Public ReadOnly Property MergeResultsTab_Exit_KeyTip() As String
            Get
                Return ResourceManager.GetString("MergeResultsTab_Exit_KeyTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Closes the &apos;Result&apos; tab..
        '''</summary>
        Public ReadOnly Property MergeResultsTab_Exit_ToolTip_Description() As String
            Get
                Return ResourceManager.GetString("MergeResultsTab_Exit_ToolTip_Description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Exit.
        '''</summary>
        Public ReadOnly Property MergeResultsTab_Exit_ToolTip_Title() As String
            Get
                Return ResourceManager.GetString("MergeResultsTab_Exit_ToolTip_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Export.
        '''</summary>
        Public ReadOnly Property MergeResultsTab_Export() As String
            Get
                Return ResourceManager.GetString("MergeResultsTab_Export", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to X.
        '''</summary>
        Public ReadOnly Property MergeResultsTab_Export_KeyTip() As String
            Get
                Return ResourceManager.GetString("MergeResultsTab_Export_KeyTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to First Record.
        '''</summary>
        Public ReadOnly Property MergeResultsTab_FirstRecord() As String
            Get
                Return ResourceManager.GetString("MergeResultsTab_FirstRecord", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to F.
        '''</summary>
        Public ReadOnly Property MergeResultsTab_FirstRecord_KeyTip() As String
            Get
                Return ResourceManager.GetString("MergeResultsTab_FirstRecord_KeyTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to First Record.
        '''</summary>
        Public ReadOnly Property MergeResultsTab_FirstRecord_ToolTip_Title() As String
            Get
                Return ResourceManager.GetString("MergeResultsTab_FirstRecord_ToolTip_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to W.
        '''</summary>
        Public ReadOnly Property MergeResultsTab_KeyTip() As String
            Get
                Return ResourceManager.GetString("MergeResultsTab_KeyTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Last Record.
        '''</summary>
        Public ReadOnly Property MergeResultsTab_LastRecord() As String
            Get
                Return ResourceManager.GetString("MergeResultsTab_LastRecord", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to L.
        '''</summary>
        Public ReadOnly Property MergeResultsTab_LastRecord_KeyTip() As String
            Get
                Return ResourceManager.GetString("MergeResultsTab_LastRecord_KeyTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Last Record.
        '''</summary>
        Public ReadOnly Property MergeResultsTab_LastRecord_ToolTip_Title() As String
            Get
                Return ResourceManager.GetString("MergeResultsTab_LastRecord_ToolTip_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Navigate.
        '''</summary>
        Public ReadOnly Property MergeResultsTab_Navigate() As String
            Get
                Return ResourceManager.GetString("MergeResultsTab_Navigate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to N.
        '''</summary>
        Public ReadOnly Property MergeResultsTab_Navigate_KeyTip() As String
            Get
                Return ResourceManager.GetString("MergeResultsTab_Navigate_KeyTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Next Record.
        '''</summary>
        Public ReadOnly Property MergeResultsTab_NextRecord() As String
            Get
                Return ResourceManager.GetString("MergeResultsTab_NextRecord", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to N.
        '''</summary>
        Public ReadOnly Property MergeResultsTab_NextRecord_KeyTip() As String
            Get
                Return ResourceManager.GetString("MergeResultsTab_NextRecord_KeyTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Next Record.
        '''</summary>
        Public ReadOnly Property MergeResultsTab_NextRecord_ToolTip_Title() As String
            Get
                Return ResourceManager.GetString("MergeResultsTab_NextRecord_ToolTip_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Previous Record.
        '''</summary>
        Public ReadOnly Property MergeResultsTab_PreviousRecord() As String
            Get
                Return ResourceManager.GetString("MergeResultsTab_PreviousRecord", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to P.
        '''</summary>
        Public ReadOnly Property MergeResultsTab_PreviousRecord_KeyTip() As String
            Get
                Return ResourceManager.GetString("MergeResultsTab_PreviousRecord_KeyTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Previous Record.
        '''</summary>
        Public ReadOnly Property MergeResultsTab_PreviousRecord_ToolTip_Title() As String
            Get
                Return ResourceManager.GetString("MergeResultsTab_PreviousRecord_ToolTip_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Go to record no. {0}..
        '''</summary>
        Public ReadOnly Property MergeResultsTab_Record_ToolTip_Description() As String
            Get
                Return ResourceManager.GetString("MergeResultsTab_Record_ToolTip_Description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Result.
        '''</summary>
        Public ReadOnly Property MergeResultsTab_Result() As String
            Get
                Return ResourceManager.GetString("MergeResultsTab_Result", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to V.
        '''</summary>
        Public ReadOnly Property MergeResultsTab_Result_KeyTip() As String
            Get
                Return ResourceManager.GetString("MergeResultsTab_Result_KeyTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Blocks.
        '''</summary>
        Public ReadOnly Property MergeSettingsDialog_Blocks() As String
            Get
                Return ResourceManager.GetString("MergeSettingsDialog_Blocks", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancel.
        '''</summary>
        Public ReadOnly Property MergeSettingsDialog_Cancel() As String
            Get
                Return ResourceManager.GetString("MergeSettingsDialog_Cancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Merge Settings.
        '''</summary>
        Public ReadOnly Property MergeSettingsDialog_Caption() As String
            Get
                Return ResourceManager.GetString("MergeSettingsDialog_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Fields.
        '''</summary>
        Public ReadOnly Property MergeSettingsDialog_Fields() As String
            Get
                Return ResourceManager.GetString("MergeSettingsDialog_Fields", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Images.
        '''</summary>
        Public ReadOnly Property MergeSettingsDialog_Images() As String
            Get
                Return ResourceManager.GetString("MergeSettingsDialog_Images", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Lines.
        '''</summary>
        Public ReadOnly Property MergeSettingsDialog_Lines() As String
            Get
                Return ResourceManager.GetString("MergeSettingsDialog_Lines", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Merge _all records.
        '''</summary>
        Public ReadOnly Property MergeSettingsDialog_MergeAllRecords() As String
            Get
                Return ResourceManager.GetString("MergeSettingsDialog_MergeAllRecords", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Merge into single document.
        '''</summary>
        Public ReadOnly Property MergeSettingsDialog_MergeIntoSingleDocument() As String
            Get
                Return ResourceManager.GetString("MergeSettingsDialog_MergeIntoSingleDocument", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Number of records:.
        '''</summary>
        Public ReadOnly Property MergeSettingsDialog_NumberOfRecords() As String
            Get
                Return ResourceManager.GetString("MergeSettingsDialog_NumberOfRecords", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OK.
        '''</summary>
        Public ReadOnly Property MergeSettingsDialog_OK() As String
            Get
                Return ResourceManager.GetString("MergeSettingsDialog_OK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Records.
        '''</summary>
        Public ReadOnly Property MergeSettingsDialog_Records() As String
            Get
                Return ResourceManager.GetString("MergeSettingsDialog_Records", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Remove empty merge elements.
        '''</summary>
        Public ReadOnly Property MergeSettingsDialog_RemoveEmptyMergeElements() As String
            Get
                Return ResourceManager.GetString("MergeSettingsDialog_RemoveEmptyMergeElements", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Trailing Whitespace.
        '''</summary>
        Public ReadOnly Property MergeSettingsDialog_TrailingWhitespace() As String
            Get
                Return ResourceManager.GetString("MergeSettingsDialog_TrailingWhitespace", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The following exception is thrown:
        '''	
        '''&quot;{0}&quot;
        '''
        '''To get help, please visit the Text Control Support at www.textcontrol.com..
        '''</summary>
        Public ReadOnly Property MessageBox_Application_ThreadException_Text() As String
            Get
                Return ResourceManager.GetString("MessageBox_Application_ThreadException_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Export Results.
        '''</summary>
        Public ReadOnly Property MessageBox_ExportMergeResultDialog_DirectoryDoesNotExist_Caption() As String
            Get
                Return ResourceManager.GetString("MessageBox_ExportMergeResultDialog_DirectoryDoesNotExist_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The specified directory does not exist..
        '''</summary>
        Public ReadOnly Property MessageBox_ExportMergeResultDialog_DirectoryDoesNotExist_Text() As String
            Get
                Return ResourceManager.GetString("MessageBox_ExportMergeResultDialog_DirectoryDoesNotExist_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Open Hyperlink.
        '''</summary>
        Public ReadOnly Property MessageBox_OpenHyperlink_CouldNotOpenLink_Caption() As String
            Get
                Return ResourceManager.GetString("MessageBox_OpenHyperlink_CouldNotOpenLink_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Could not open link to &apos;{0}&apos;..
        '''</summary>
        Public ReadOnly Property MessageBox_OpenHyperlink_CouldNotOpenLink_Text() As String
            Get
                Return ResourceManager.GetString("MessageBox_OpenHyperlink_CouldNotOpenLink_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Open linked File.
        '''</summary>
        Public ReadOnly Property MessageBox_OpenHyperlink_FileDoesNotExist_Caption() As String
            Get
                Return ResourceManager.GetString("MessageBox_OpenHyperlink_FileDoesNotExist_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The linked file &apos;{0}&apos; does not exist..
        '''</summary>
        Public ReadOnly Property MessageBox_OpenHyperlink_FileDoesNotExist_Text() As String
            Get
                Return ResourceManager.GetString("MessageBox_OpenHyperlink_FileDoesNotExist_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Open Recent File.
        '''</summary>
        Public ReadOnly Property MessageBox_OpenRecentFile_FileDoesNotExist_Caption() As String
            Get
                Return ResourceManager.GetString("MessageBox_OpenRecentFile_FileDoesNotExist_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The selected file does not exist. Do you want to remove it from the list of recent files?.
        '''</summary>
        Public ReadOnly Property MessageBox_OpenRecentFile_FileDoesNotExist_Text() As String
            Get
                Return ResourceManager.GetString("MessageBox_OpenRecentFile_FileDoesNotExist_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Incorrect Password.
        '''</summary>
        Public ReadOnly Property MessageBox_PasswordDialog_IncorrectPassword_Caption() As String
            Get
                Return ResourceManager.GetString("MessageBox_PasswordDialog_IncorrectPassword_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The entered password is incorrect..
        '''</summary>
        Public ReadOnly Property MessageBox_PasswordDialog_IncorrectPassword_Text() As String
            Get
                Return ResourceManager.GetString("MessageBox_PasswordDialog_IncorrectPassword_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Exit.
        '''</summary>
        Public ReadOnly Property MessageBox_SaveDirtyDocumentOnExit_Caption() As String
            Get
                Return ResourceManager.GetString("MessageBox_SaveDirtyDocumentOnExit_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you want to save changes to &apos;{0}&apos; before the program closes? 
        '''Click Yes to save and close, No to close without saving, or Cancel to not close..
        '''</summary>
        Public ReadOnly Property MessageBox_SaveDirtyDocumentOnExit_ToFile() As String
            Get
                Return ResourceManager.GetString("MessageBox_SaveDirtyDocumentOnExit_ToFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you want to save the document before the program closes? 
        '''Click Yes to save and close, No to close without saving, or Cancel to not close..
        '''</summary>
        Public ReadOnly Property MessageBox_SaveDirtyDocumentOnExit_Untitled() As String
            Get
                Return ResourceManager.GetString("MessageBox_SaveDirtyDocumentOnExit_Untitled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New.
        '''</summary>
        Public ReadOnly Property MessageBox_SaveDirtyDocumentOnNew_Caption() As String
            Get
                Return ResourceManager.GetString("MessageBox_SaveDirtyDocumentOnNew_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you want to save changes to &apos;{0}&apos; before a new document is created? 
        '''Click Yes to save and create, No to create without saving, or Cancel to not to create a new document.
        '''</summary>
        Public ReadOnly Property MessageBox_SaveDirtyDocumentOnNew_ToFile() As String
            Get
                Return ResourceManager.GetString("MessageBox_SaveDirtyDocumentOnNew_ToFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you want to save the document before a new document is created? 
        '''Click Yes to save and create, No to create without saving, or Cancel to not to create a new document.
        '''</summary>
        Public ReadOnly Property MessageBox_SaveDirtyDocumentOnNew_Untitled() As String
            Get
                Return ResourceManager.GetString("MessageBox_SaveDirtyDocumentOnNew_Untitled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Open.
        '''</summary>
        Public ReadOnly Property MessageBox_SaveDirtyDocumentOnOpen_Caption() As String
            Get
                Return ResourceManager.GetString("MessageBox_SaveDirtyDocumentOnOpen_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you want to save changes to &apos;{0}&apos; before the new document is opened? 
        '''Click Yes to save and open, No to open without saving, or Cancel to not to open the new document.
        '''</summary>
        Public ReadOnly Property MessageBox_SaveDirtyDocumentOnOpen_ToFile() As String
            Get
                Return ResourceManager.GetString("MessageBox_SaveDirtyDocumentOnOpen_ToFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you want to save the document before the new document is opened? 
        '''Click Yes to save and open, No to open without saving, or Cancel to not to open the new document.
        '''</summary>
        Public ReadOnly Property MessageBox_SaveDirtyDocumentOnOpen_Untitled() As String
            Get
                Return ResourceManager.GetString("MessageBox_SaveDirtyDocumentOnOpen_Untitled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancel.
        '''</summary>
        Public ReadOnly Property PasswordDialog_Cancel() As String
            Get
                Return ResourceManager.GetString("PasswordDialog_Cancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Password.
        '''</summary>
        Public ReadOnly Property PasswordDialog_Caption() As String
            Get
                Return ResourceManager.GetString("PasswordDialog_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter a password to open the document.
        '''</summary>
        Public ReadOnly Property PasswordDialog_EnterPassword() As String
            Get
                Return ResourceManager.GetString("PasswordDialog_EnterPassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OK.
        '''</summary>
        Public ReadOnly Property PasswordDialog_OK() As String
            Get
                Return ResourceManager.GetString("PasswordDialog_OK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Password:.
        '''</summary>
        Public ReadOnly Property PasswordDialog_Password() As String
            Get
                Return ResourceManager.GetString("PasswordDialog_Password", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The document &apos;{0}&apos; is protected..
        '''</summary>
        Public ReadOnly Property PasswordDialog_ProtectedDocument() As String
            Get
                Return ResourceManager.GetString("PasswordDialog_ProtectedDocument", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Load Sample Database.
        '''</summary>
        Public ReadOnly Property RibbonReportingTab_LoadSampleDatabase() As String
            Get
                Return ResourceManager.GetString("RibbonReportingTab_LoadSampleDatabase", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Load a sample database..
        '''</summary>
        Public ReadOnly Property RibbonReportingTab_LoadSampleDatabase_ToolTip_Description() As String
            Get
                Return ResourceManager.GetString("RibbonReportingTab_LoadSampleDatabase_ToolTip_Description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Load Sample Database.
        '''</summary>
        Public ReadOnly Property RibbonReportingTab_LoadSampleDatabase_ToolTip_Title() As String
            Get
                Return ResourceManager.GetString("RibbonReportingTab_LoadSampleDatabase_ToolTip_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Column: .
        '''</summary>
        Public ReadOnly Property StatusBar_Column() As String
            Get
                Return ResourceManager.GetString("StatusBar_Column", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Line: .
        '''</summary>
        Public ReadOnly Property StatusBar_Line() As String
            Get
                Return ResourceManager.GetString("StatusBar_Line", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Page: .
        '''</summary>
        Public ReadOnly Property StatusBar_Page() As String
            Get
                Return ResourceManager.GetString("StatusBar_Page", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Section: .
        '''</summary>
        Public ReadOnly Property StatusBar_Section() As String
            Get
                Return ResourceManager.GetString("StatusBar_Section", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
